version: '3'

services:
  app:
    image: node:12.18.3-slim
    restart: always
    working_dir: /usr/src/app
    env_file: .env
    environment: 
      - MONGO_HOST=mongo
    ports:
      - 3000:3000
    depends_on: 
      - mongo
    volumes:
      - ./:/usr/src/app
    command: npm run start
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017